# Generated by Django 6.0.6 on 2026-07-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment_payment_url_payment_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод на счет'), ('card', 'Банковская карта')], default='card', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
