# Generated by Django 6.0.6 on 2026-07-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на оплату'),
        ),
    ]
