# Generated by Django 6.0.6 on 2026-07-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_payment_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(default='pending', help_text='pending, paid, canceled', max_length=50, verbose_name='Статус платежа'),
        ),
    ]
