name: Django CI/CD Pipeline

on:
  push:
    branches: [ base_develop ]
  pull_request:
    branches: [ base_develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Linter (PEP 8 check)
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run tests
        env:
          SECRET_KEY: 'django-insecure-test-key-for-github-actions-automation'
          DEBUG: 'True'
        run: python manage.py test

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/base_develop' && github.event_name == 'push'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in Docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/education_system:${{ github.sha }} .

      - name: Push Docker image in Docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/education_system:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Generate local .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Copy .env file to server
        run: |
          ssh -v -T -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p ~/education_system"
          scp -o StrictHostKeyChecking=no .env ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/education_system/.env

      - name: Deploy to server
        run: |
          ssh -v -T -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/education_system:${{ github.sha }}
          docker stop myapp education_system || true
          docker rm myapp education_system || true
          docker run -d --name education_system -p 80:8000 --network="host" --env-file ~/education_system/.env --restart always ${{ secrets.DOCKER_USERNAME }}/education_system:${{ github.sha }}
          sleep 3
          docker exec -i education_system python manage.py migrate
          EOF
